### PR TITLE
Linux61 backports

### PR DESCRIPTION
**Pull request by Redecorating**
backport:

- battery charge limiter in sysfs
- gmux

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
Do we intend to upstream apple-set-os?

**Comment by AdityaGarg8** [comment]
I haven't tested this yet, but iirc there was something upstreamed in Linux 6.2 which also had to be backported to 6.1?

**Comment by AdityaGarg8** [comment]
https://lore.kernel.org/all/20230123113750.462144-2-hdegoede@redhat.com/

This one

**Comment by Redecorating** [comment]
i checked and those patches have already been back-ported to 6.1 stable

**Comment by Redecorating** [comment]
> Do we intend to upstream apple-set-os?

eventually i'd hope so

**Comment by AdityaGarg8** [comment]
How to use with systemd boot?

**Comment by Redecorating** [comment]
systemdboot doesn't exit the efiruntime services, so once systemd-boot starts the linux kernel, linux will be able to do apple-set-os itself. The user won't have to set anything up (hopefully)

**Comment by AdityaGarg8** [comment]
If that's the case, this should be an optional feature imo

**Comment by Redecorating** [comment]
> If that's the case, this should be an optional feature imo

when do you think it wouldn't be wanted?

regardless i'll revert that commit for now so we can merge this and figure the set-os patch out later

**Comment by AdityaGarg8** [comment]
> when do you think it wouldn't be wanted?
> 

For users who wish to keep the dGPU only the Apple way

> regardless i'll revert that commit for now so we can merge this and figure the set-os patch out later

**Review by AdityaGarg8 — APPROVED** [review]

**Pull request merged**
